name: my_web_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.6
  intl: ^0.19.0                    # 日付フォーマット
  flutter_markdown: ^0.7.4+1       # マークダウンレンダリング
  url_launcher: ^6.3.1             # リンククリック対応
  markdown: ^7.2.2                 # マークダウンパース
  highlight: ^0.7.0                # シンタックスハイライト
  shared_preferences: ^2.3.3       # 追加：ローカルストレージ
  provider: ^6.1.2  # 追加
  file_picker: ^8.1.2  # 追加
  mime: ^1.0.6  # 追加
  path: ^1.9.0  # 追加
  google_fonts: ^6.1.0  # 追加

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true